projects:
  app:
    schemaPath: 'src/schema.graphql'
    extensions:
      endpoints:
        default: 'http://localhost:4444'
  prisma:
    schemaPath: 'src/generated/prisma.graphql'
    extensions:
      prisma: prisma.yml

# endpoint: ${env:PRISMA_ENDPOINT}
# # endpoint: https://grown-farms-db-497270b455.herokuapp.com/backend/prod
# datamodel: datamodel.graphql
# secret: ${env:PRISMA_SECRET}
# hooks:
#   post-deploy:
#     - graphql get-schema -p prisma
